In [1]:
import numpy as np

In [2]:
arr = np.arange(12).reshape((3, 4))

In [3]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
condition = np.mod(arr, 3)==0

In [5]:
condition

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [6]:
np.extract(condition, arr)

array([0, 3, 6, 9])

In [7]:
arr[condition]

array([0, 3, 6, 9])